tgt_dir = ARGV[0]
abort("tgt_dir required") if tgt_dir.empty?

abort("#{tgt_dir} does not exist") if !Dir.exist?(tgt_dir)
puts "FIX: #{tgt_dir}"

img_files = File.join(tgt_dir, "**", "*.jpg")
Dir.glob(img_files).each do |f|
   base_fn = File.basename(f, File.extname(f))
   puts base_fn
   tfn = "#{base_fn}-150x150#{File.extname(f).downcase}"
   img_path = File.dirname f
   thumb_fn = File.join(img_path, tfn)
   # NOTE: the old WP site makes all derivatives extensions lowercase regardless of original.
   # Make it the same here. This also controls the naming of the thumbs generated by this service.
   cmd = "convert -quiet -resize 150x150^ -extent 150x150 -gravity center #{f} #{thumb_fn}"
   `#{cmd}`
end
