update submissions set institution_id=(select id from institutions where name="Virginia Union University") where library=", VUU";
update submissions set institution_id=(select id from institutions where name="Ohio State University") where library="Alden Library";
update submissions set institution_id=(select id from institutions where name="Ohio State University") where library="Alden Library at Ohio University";
update submissions set institution_id=(select id from institutions where name="University of Virginia") where library="Alderman";
update submissions set institution_id=(select id from institutions where name="University of Virginia") where library="Alderman Library";
update submissions set institution_id=(select id from institutions where name="University of Virginia") where library="Alderman Library (University of Virginia)";
update submissions set institution_id=(select id from institutions where name="University of Virginia") where library="Alderman Library at the University of Virginia";
update submissions set institution_id=(select id from institutions where name="University of Virginia") where library="Alderman Library, University of Virginia";
update submissions set institution_id=(select id from institutions where name="American Bookbinders Museum") where library="American Bookbinders Museum";
update submissions set institution_id=(select id from institutions where name="Arizona State University") where library="Arizona State University";
update submissions set institution_id=(select id from institutions where name="Arizona State University") where library="Arizona State University Hayden Library";
update submissions set institution_id=(select id from institutions where name="Long Island University") where library="B. Davis Schwartz Memorial Library, LIU Post";
update submissions set institution_id=(select id from institutions where name="Open University") where library="Betty Boothroyd Library, The Open University, Milton Keynes";
update submissions set institution_id=(select id from institutions where name="University of Richmond") where library="Boatwright, University of Richmond";
update submissions set institution_id=(select id from institutions where name="Boston Public Library") where library="Boston Public Libary";
update submissions set institution_id=(select id from institutions where name="Boston Public Library") where library="Boston Public Library";
update submissions set institution_id=(select id from institutions where name="Boston Public Library") where library="Boston Public Library (Main Branch)";
update submissions set institution_id=(select id from institutions where name="Boston Public Library") where library="Boston Public Library - Main Branch";
update submissions set institution_id=(select id from institutions where name="Boston Public Library") where library="Boston Public Library Rare Books Collection";
update submissions set institution_id=(select id from institutions where name="Boston Public Library") where library="Boston Public Library, central branch";
update submissions set institution_id=(select id from institutions where name="Boston Public Library") where library="Boston Public Library, Copley";
update submissions set institution_id=(select id from institutions where name="Boston Public Library") where library="Boston Public Library- Main Branch";
update submissions set institution_id=(select id from institutions where name="Boston Public Library") where library="Boston Public Library--Main Branch";
update submissions set institution_id=(select id from institutions where name="Boston Public Library") where library="Boston Public Library-Main Branch";
update submissions set institution_id=(select id from institutions where name="British Library") where library="British Library";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Butler";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Butler Library";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Butler library (Columbia University)";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Butler Library (Columbia)";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Butler Library at Columbia University";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Butler library, Columbia U";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Butler Library, Columbia University";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Butler Library, Columbia University in the City of New York";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Butler Stacks";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Butler Stacks (Columbia)";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Butler stacks, Columbia";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Butler Stacks, Columbia University";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Butler, Columbia";
update submissions set institution_id=(select id from institutions where name="James Madison University") where library="Carrier Library, JMU";
update submissions set institution_id=(select id from institutions where name="College of the Holy Cross") where library="College of the Holy Cross";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Colombia";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Columbia Butler";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Columbia Butler Lib.";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Columbia University (Butler Library)";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Columbia University - Butler Library";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Columbia University Butler Library";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Columbia University Butler Library Stacks";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Columbia University Library";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Columbia University, Butler Library";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Columbia University: Butler Library";
update submissions set institution_id=(select id from institutions where name="Columbia University") where library="Columbia, Butler";
update submissions set institution_id=(select id from institutions where name="University of South Carolina ") where library="Cooper, U South Carolina";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="D H Hill Library";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="D. H. Hill";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="D. H. Hill Library";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="D. H. Hill Library at North Carolina State University";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="D. H. Hill Library, North Carolina State University";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="D. H. Hill of North Carolina State University";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="D.H. Hill";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="D.H. Hill library";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="D.H. Hill Library at NC State";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="D.H. Hill Library North Carolina";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="D.H. Hill Library, NC State University, Raleigh, NC";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="D.H. Hill Library, NCSU";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="DH Hill Library";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="DH Hill Library NCSU";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="DH Hill Library, NC State University";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="DH Hill, NC State Univ";
update submissions set institution_id=(select id from institutions where name="College of the Holy Cross") where library="Dinand";
update submissions set institution_id=(select id from institutions where name="College of the Holy Cross") where library="Dinand Libary, College of the Holy Cross";
update submissions set institution_id=(select id from institutions where name="College of the Holy Cross") where library="Dinand library";
update submissions set institution_id=(select id from institutions where name="College of the Holy Cross") where library="Dinand Library Holy Cross";
update submissions set institution_id=(select id from institutions where name="College of the Holy Cross") where library="Dinand Library, College of the Holy Cross";
update submissions set institution_id=(select id from institutions where name="College of the Holy Cross") where library="Dinand Library, College of the Holy Cross, Worcester, MA";
update submissions set institution_id=(select id from institutions where name="College of the Holy Cross") where library="Dinned Library, College of the Holy Cross";
update submissions set institution_id=(select id from institutions where name="San Jose State University ") where library="Dr. Martin Luther King Jr Library";
update submissions set institution_id=(select id from institutions where name="San Jose State University ") where library="Dr. Martin Luther King Jr. Library";
update submissions set institution_id=(select id from institutions where name="San Jose State University ") where library="DR. MARTIN LUTHER KING LIBRARY";
update submissions set institution_id=(select id from institutions where name="San Jose State University ") where library="Dr. Martin Luther King, Jr. Library";
update submissions set institution_id=(select id from institutions where name="University of Louisville") where library="Ekstrom Library, U Louisville";
update submissions set institution_id=(select id from institutions where name="University of Missouri") where library="Ellis LIbrary, Rare Books and Special Collections, Columbia, MO";
update submissions set institution_id=(select id from institutions where name="Fred W. Smith ") where library="Fred W. Smith National Library for the Study of George Washington";
update submissions set institution_id=(select id from institutions where name="Georgetown College") where library="Georgetown College Library, Georgetown, KY";
update submissions set institution_id=(select id from institutions where name="Rosemont College") where library="Gertrude Kistler Memorial Library, Rosemont College";
update submissions set institution_id=(select id from institutions where name="Mary Baldwin University") where library="Grafton Library, Mary Baldwin";
update submissions set institution_id=(select id from institutions where name="Grove City College") where library="Grove City College Henry Buhl Library";
update submissions set institution_id=(select id from institutions where name="University of Michigan ") where library="Harlan Hatcher Graduate Library, University of Michigan";
update submissions set institution_id=(select id from institutions where name="Eastern Mennonite University") where library="Hartzler Library, EMU";
update submissions set institution_id=(select id from institutions where name="Arizona State University") where library="Hayden Library, Arizona State University";
update submissions set institution_id=(select id from institutions where name="Grove City College") where library="Henry Buhl Library";
update submissions set institution_id=(select id from institutions where name="Grove City College") where library="Henry Buhl Library Grove City College";
update submissions set institution_id=(select id from institutions where name="Grove City College") where library="Henry Buhl Library of Grove City College";
update submissions set institution_id=(select id from institutions where name="Grove City College") where library="Henry Buhl Library, Grove City College";
update submissions set institution_id=(select id from institutions where name="Grove City College") where library="Henry Buhl Library, Grove City College, Grove City, PA";
update submissions set institution_id=(select id from institutions where name="Hofstra University") where library="Hofstra, Axinn Library";
update submissions set institution_id=(select id from institutions where name="Hofstra University") where library="Hoftstra, Axinn Library";
update submissions set institution_id=(select id from institutions where name="Hope College ") where library="Hope College Library";
update submissions set institution_id=(select id from institutions where name="Hope College ") where library="Hope College Van Wylen Library";
update submissions set institution_id=(select id from institutions where name="") where library="Inquiring Minds Bookstore";
update submissions set institution_id=(select id from institutions where name="Iowa State University") where library="Iowa";
update submissions set institution_id=(select id from institutions where name="University of Virginia") where library="Ivy Stacks";
update submissions set institution_id=(select id from institutions where name="University of Virginia") where library="Ivy Stacks, U Virginia";
update submissions set institution_id=(select id from institutions where name="Virginia Commonwealth University") where library="James Branch Cabell Library, VCU";
update submissions set institution_id=(select id from institutions where name="Emory and Henry College") where library="Kelly Library, Emory and Henry";
update submissions set institution_id=(select id from institutions where name="Georgetown University") where library="Lauinger Library";
update submissions set institution_id=(select id from institutions where name="Georgetown University") where library="Lauinger Library, Georgetown University";
update submissions set institution_id=(select id from institutions where name="Lehigh University") where library="Lehigh University";
update submissions set institution_id=(select id from institutions where name="Washington and Lee University") where library="Leyburn Library, Washington and Lee";
update submissions set institution_id=(select id from institutions where name="University of Virginia") where library="Library of the University of Virginia";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="Library State Normal School, New Paltz";
update submissions set institution_id=(select id from institutions where name="University of Nevada - Las Vegas") where library="Lied Library";
update submissions set institution_id=(select id from institutions where name="Lehigh University") where library="Linderman Library, Lehigh University";
update submissions set institution_id=(select id from institutions where name="University of Nebraska - Lincoln") where library="Love at UNL";
update submissions set institution_id=(select id from institutions where name="University of Nebraska - Lincoln") where library="Love Library, University of Nebraska-Lincoln";
update submissions set institution_id=(select id from institutions where name="University of Nebraska - Lincoln") where library="Love Library, UNL";
update submissions set institution_id=(select id from institutions where name="University of Nebraska - Lincoln") where library="Love Library, UNLPS";
update submissions set institution_id=(select id from institutions where name="University of Victoria") where library="Macpherson Library";
update submissions set institution_id=(select id from institutions where name="Wellesley College") where library="Margaret Clapp Library at Wellesley College";
update submissions set institution_id=(select id from institutions where name="San Jose State University") where library="Martin Luther King Jr. Library San Jose State University";
update submissions set institution_id=(select id from institutions where name="San Jose State University") where library="Martin Luther King Jr. Library, San Jose, Ca";
update submissions set institution_id=(select id from institutions where name="San Jose State University") where library="Martin Luther King Library";
update submissions set institution_id=(select id from institutions where name="San Jose State University") where library="Martin Luther King Library, SJSU";
update submissions set institution_id=(select id from institutions where name="University of Victoria") where library="McPherson";
update submissions set institution_id=(select id from institutions where name="University of Victoria") where library="McPherson Library";
update submissions set institution_id=(select id from institutions where name="University of Victoria") where library="McPherson Library, University of Victoria";
update submissions set institution_id=(select id from institutions where name="University of Victoria") where library="McPherson Library, University of Victoria, Canada";
update submissions set institution_id=(select id from institutions where name="University of Victoria") where library="McPherson Library, Uvic";
update submissions set institution_id=(select id from institutions where name="Millsaps College") where library="Millsaps College";
update submissions set institution_id=(select id from institutions where name="Millsaps College") where library="Millsaps College Libary";
update submissions set institution_id=(select id from institutions where name="Millsaps College") where library="Millsaps College Library";
update submissions set institution_id=(select id from institutions where name="Mount Holyoke College") where library="Mount Holyoke College";
update submissions set institution_id=(select id from institutions where name="Mount Holyoke College") where library="Mount Holyoke College Library";
update submissions set institution_id=(select id from institutions where name="Mount Holyoke College") where library="Mount Holyoke College, South Hadley, Massachusetts";
update submissions set institution_id=(select id from institutions where name="Mount Holyoke College") where library="Mount Holyoke Williston Library";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="N.C. State University's D.H. Hill Library";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="NC State University";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="NC State University D.H. Hill Library";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="NC State University Library";
update submissions set institution_id=(select id from institutions where name="Virginia Polytechnic and State University") where library="Newman Library, Virginia Tech";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="North Carolina State University";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="North Carolina State University (DH Hill Library)";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="North Carolina State University, D.H. Hill Library";
update submissions set institution_id=(select id from institutions where name="North Carolina State University") where library="North Carolina state university- D. H Hill Library";
update submissions set institution_id=(select id from institutions where name="Northeastern University") where library="Northeastern";
update submissions set institution_id=(select id from institutions where name="Northeastern University") where library="Northeastern Collections and Archives";
update submissions set institution_id=(select id from institutions where name="Northeastern University") where library="Northeastern Library";
update submissions set institution_id=(select id from institutions where name="Northeastern University") where library="Northeastern University";
update submissions set institution_id=(select id from institutions where name="Northeastern University") where library="Northeastern University (Boston, MA)";
update submissions set institution_id=(select id from institutions where name="Northeastern University") where library="Northeastern University Archives and Special Collecios";
update submissions set institution_id=(select id from institutions where name="Northeastern University") where library="Northeastern University Archives and Special Collections";
update submissions set institution_id=(select id from institutions where name="Northeastern University") where library="Northeastern University Library";
update submissions set institution_id=(select id from institutions where name="Northeastern University") where library="Northeastern University Snell Library Archives";
update submissions set institution_id=(select id from institutions where name="Northeastern University") where library="Northeastern University Special Archives";
update submissions set institution_id=(select id from institutions where name="Northeastern University") where library="Northeastern University Special Collections";
update submissions set institution_id=(select id from institutions where name="Northeastern University") where library="Northeastern University Special Collections Library";
update submissions set institution_id=(select id from institutions where name="Northeastern University") where library="Northeastern University, Special Collections";
update submissions set institution_id=(select id from institutions where name="Northumbria University ") where library="Northumbria";
update submissions set institution_id=(select id from institutions where name="Northumbria University ") where library="Northumbria City Campus Library";
update submissions set institution_id=(select id from institutions where name="Northumbria University") where library="Northumbria Library";
update submissions set institution_id=(select id from institutions where name="Northumbria University ") where library="Northumbria Univeristy Library";
update submissions set institution_id=(select id from institutions where name="Northumbria University ") where library="Northumbria University";
update submissions set institution_id=(select id from institutions where name="Northumbria University ") where library="Northumbria University City Campus Library";
update submissions set institution_id=(select id from institutions where name="Northumbria University ") where library="Northumbria University City Campus Libray";
update submissions set institution_id=(select id from institutions where name="Northumbria University ") where library="Northumbria University Library";
update submissions set institution_id=(select id from institutions where name="Northumbria University ") where library="Northumrbia University Library";
update submissions set institution_id=(select id from institutions where name="Roanoke College") where library="not available, Roanoke College";
update submissions set institution_id=(select id from institutions where name="New York University") where library="NYU Bobst Library";
update submissions set institution_id=(select id from institutions where name="Ohio State University") where library="Ohio University Alden Library";
update submissions set institution_id=(select id from institutions where name="Ohio State University") where library="Ohio University Library";
update submissions set institution_id=(select id from institutions where name="Ohio State University") where library="Ohio University's Alden Library";
update submissions set institution_id=(select id from institutions where name="Oklahoma State University") where library="Oklahoma State University Edmon Low Library";
update submissions set institution_id=(select id from institutions where name="Virginia Military Institute") where library="Preston Library, VMI";
update submissions set institution_id=(select id from institutions where name="University of North Carolina - Chapel Hill") where library="Rare Book Collection, Wilson Library, University of North Carolina at Chapel Hill";
update submissions set institution_id=(select id from institutions where name="Rhodes College") where library="Rhodes College Barret Library";
update submissions set institution_id=(select id from institutions where name="University of Miami") where library="Richter library";
update submissions set institution_id=(select id from institutions where name="University of Miami") where library="Richter, U Miami";
update submissions set institution_id=(select id from institutions where name="University of Miami") where library="ritcher";
update submissions set institution_id=(select id from institutions where name="University of Miami") where library="Ritcher Library";
update submissions set institution_id=(select id from institutions where name="Ryerson University ") where library="Ryerson";
update submissions set institution_id=(select id from institutions where name="Ryerson University ") where library="Ryerson Library";
update submissions set institution_id=(select id from institutions where name="Ryerson University ") where library="Ryerson University";
update submissions set institution_id=(select id from institutions where name="Ryerson University ") where library="Ryerson University Library";
update submissions set institution_id=(select id from institutions where name="Ryerson University ") where library="Ryerson University Library and Archives";
update submissions set institution_id=(select id from institutions where name="San Jose State University") where library="San Jose State library";
update submissions set institution_id=(select id from institutions where name="San Jose State University") where library="San Jose State Library (MLK Library)";
update submissions set institution_id=(select id from institutions where name="San Jose State University") where library="San Jose State Library, Martin Luther King Jr. Library";
update submissions set institution_id=(select id from institutions where name="San Jose State University") where library="San Jose State University";
update submissions set institution_id=(select id from institutions where name="San Jose State University") where library="SJSU Dr. Martin Luther King, JR. Library";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="Sojourner Trith Library - SUNY New Paltz";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="Sojourner Truth Library";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="Sojourner Truth Library ( SUNY New Paltz)";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="Sojourner Truth Library - SUNY at New Paltz";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="Sojourner Truth Library - SUNY New Paltz";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="Sojourner Truth Library @ SUNY New Paltz";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="Sojourner Truth Library at SUNY New Paltz";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="Sojourner Truth Library in Suny New Paltz";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="Sojourner Truth Library on SUNY New Paltz campus";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="Sojourner Truth Library SUNY New Paltz";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="Sojourner Truth Library, New Paltz NY";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="Sojourner Truth Library, New Paltz, NY";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="Sojourner Truth Library, State Un";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="Sojourner Truth Library, SUNY New Paltz";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="Sojourner Truth Library, SUNY New Paltz, NY";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="Sojourner Truth Library- SUNY New Paltz";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="Sojourner Truth Library/ SUNY New Paltz";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="Sojourner Truth Library/SUNY New Paltz";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="Soujourner Truth Library";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="Sourjourner Truth";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="Special Collections and Archives at Northeastern University";
update submissions set institution_id=(select id from institutions where name="Loyola University Chicago") where library="Special Collections, Loyola University Chicago";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="State Universit of New York at New Paltz";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="State University New Platz, NY";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="State University of New York at New Paltz";
update submissions set institution_id=(select id from institutions where name="Yale University") where library="Sterling Memorial Library, Yale University";
update submissions set institution_id=(select id from institutions where name="Yale University") where library="Sterling Memorial, Yale U";
update submissions set institution_id=(select id from institutions where name="") where library="Sub basement";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="SUNY New Paltz";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="SUNY New Paltz library";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="SUNY New Paltz Sojourner Truth Library";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="SUNY New Paltz STL";
update submissions set institution_id=(select id from institutions where name="State University of New York - New Paltz") where library="Suny Newpaltz Library";
update submissions set institution_id=(select id from institutions where name="William and Mary University") where library="SWEM, William and Mary";
update submissions set institution_id=(select id from institutions where name="Texas A&M University") where library="Texas A&amp;M University Evans Library";
update submissions set institution_id=(select id from institutions where name="Texas A&M University") where library="Texas A&amp;M University-Evans Library";
update submissions set institution_id=(select id from institutions where name="Texas A&M University") where library="Texas A&amp;M University-Evans Librarys";
update submissions set institution_id=(select id from institutions where name="University of Calgary") where library="TFDL, University of Calgary";
update submissions set institution_id=(select id from institutions where name="Boston Public Library") where library="The Boston Public Library";
update submissions set institution_id=(select id from institutions where name="North Carolina State University ") where library="The D.H. Hill Library North Carolina State University";
update submissions set institution_id=(select id from institutions where name="Hunter College ") where library="The Library of Associated Colleges of Upper New York";
update submissions set institution_id=(select id from institutions where name="University of Victoria") where library="The Library of University of Victory";
update submissions set institution_id=(select id from institutions where name="University of Iowa") where library="The University of Iowa Main Library";
update submissions set institution_id=(select id from institutions where name="University of Queensland") where library="The University of Queensland Library, Australia";
update submissions set institution_id=(select id from institutions where name="University of South Carolina") where library="Thomas Cooper";
update submissions set institution_id=(select id from institutions where name="University of South Carolina") where library="Thomas Cooper - University of South Carolina";
update submissions set institution_id=(select id from institutions where name="University of South Carolina") where library="Thomas Cooper at USC";
update submissions set institution_id=(select id from institutions where name="University of South Carolina") where library="Thomas Cooper Library";
update submissions set institution_id=(select id from institutions where name="University of South Carolina") where library="Thomas Cooper Library (University of South Carolina)";
update submissions set institution_id=(select id from institutions where name="University of South Carolina") where library="Thomas Cooper Library -- University of South Carolina";
update submissions set institution_id=(select id from institutions where name="University of South Carolina") where library="Thomas Cooper Library at the University of South Carolina";
update submissions set institution_id=(select id from institutions where name="University of South Carolina") where library="Thomas Cooper Library at USC";
update submissions set institution_id=(select id from institutions where name="University of South Carolina") where library="Thomas Cooper Library USC";
update submissions set institution_id=(select id from institutions where name="University of South Carolina") where library="Thomas Cooper Library, South Carolina";
update submissions set institution_id=(select id from institutions where name="University of South Carolina") where library="Thomas Cooper Library, University of South Carolina";
update submissions set institution_id=(select id from institutions where name="University of South Carolina") where library="Thomas Cooper Memorial Library";
update submissions set institution_id=(select id from institutions where name="University of South Carolina") where library="Thomas Cooper, University of South Carolina";
update submissions set institution_id=(select id from institutions where name="Tufts University") where library="Tics Library, Tufts University";
update submissions set institution_id=(select id from institutions where name="Tufts University") where library="Tisch Library, Tufts University";
update submissions set institution_id=(select id from institutions where name="Tufts University") where library="Tufts University Tisch Library";
update submissions set institution_id=(select id from institutions where name="University of Victoria") where library="U Victoria";
update submissions set institution_id=(select id from institutions where name="University of Miami") where library="UM";
update submissions set institution_id=(select id from institutions where name="University of Miami") where library="Univeristy of Miami Richter Library";
update submissions set institution_id=(select id from institutions where name="University of Montreal") where library="Université de Montréal";
update submissions set institution_id=(select id from institutions where name="University of Nevada - Las Vegas") where library="University Libraries, University of Nevada Las Vegas";
update submissions set institution_id=(select id from institutions where name="University of Nevada - Las Vegas") where library="University Libraries, University of Nevada, Las Vegas";
update submissions set institution_id=(select id from institutions where name="University of British Columbia") where library="University of British Columbia Koerner Library";
update submissions set institution_id=(select id from institutions where name="University of Calgary") where library="University of Calgary, Taylor Family Digital Library";
update submissions set institution_id=(select id from institutions where name="University of Connecticut ") where library="University of Connecticut-Storrs, Babbidge Library";
update submissions set institution_id=(select id from institutions where name="University of Iowa") where library="University of Iowa";
update submissions set institution_id=(select id from institutions where name="University of Iowa") where library="University of Iowa Main Library";
update submissions set institution_id=(select id from institutions where name="University of Iowa") where library="University of Iowa, Main Library";
update submissions set institution_id=(select id from institutions where name="University of Mephis") where library="University of Memphis, McWherter Library";
update submissions set institution_id=(select id from institutions where name="University of Miami") where library="University of Miami";
update submissions set institution_id=(select id from institutions where name="University of Miami") where library="University of Miami richter";
update submissions set institution_id=(select id from institutions where name="University of Missouri") where library="University of Missouri Libraries Depository 2";
update submissions set institution_id=(select id from institutions where name="University of Nebraska - Lincoln") where library="University of Nebraska-Lincoln";
update submissions set institution_id=(select id from institutions where name="University of Pennsylvania") where library="University of Pennsylvania - Van Pelt";
update submissions set institution_id=(select id from institutions where name="University of Queensland") where library="University of Queensland Library, Australia";
update submissions set institution_id=(select id from institutions where name="University of South Carolina") where library="University of S Carolina Irvin Dept of Rare Books and Special Collections";
update submissions set institution_id=(select id from institutions where name="University of South Carolina") where library="University of South Carolina";
update submissions set institution_id=(select id from institutions where name="University of South Carolina") where library="University of South Carolina - Thomas Cooper Library";
update submissions set institution_id=(select id from institutions where name="University of South Carolina") where library="University of South Carolina Thomas Cooper Library";
update submissions set institution_id=(select id from institutions where name="University of South Carolina") where library="University of South Carolina, Rare Books";
update submissions set institution_id=(select id from institutions where name="University of South Carolina") where library="University of South Carolina, Thomas Cooper";
update submissions set institution_id=(select id from institutions where name="University of South Carolina") where library="University of South Carolina, Thomas Cooper Lib";
update submissions set institution_id=(select id from institutions where name="University of Tennessee - Chattanooga") where library="University of Tennessee at Chattanooga";
update submissions set institution_id=(select id from institutions where name="University of Victoria") where library="University of Victoria";
update submissions set institution_id=(select id from institutions where name="University of Victoria") where library="University of Victoria (McPherson Library)";
update submissions set institution_id=(select id from institutions where name="University of Victoria") where library="University of Victoria - McPherson Library";
update submissions set institution_id=(select id from institutions where name="University of Victoria") where library="University of Victoria Library";
update submissions set institution_id=(select id from institutions where name="University of Victoria") where library="University of Victoria McPherson Library";
update submissions set institution_id=(select id from institutions where name="University of Victoria") where library="University of Victoria, BC";
update submissions set institution_id=(select id from institutions where name="University of Victoria") where library="University of Victoria, Canada";
update submissions set institution_id=(select id from institutions where name="University of Virginia") where library="University of Virginia";
update submissions set institution_id=(select id from institutions where name="University of Virginia") where library="University of Virginia Alderman Library";
update submissions set institution_id=(select id from institutions where name="University of Virginia") where library="University of Virginia, Alderman Library";
update submissions set institution_id=(select id from institutions where name="University of Waterloo") where library="University of Waterloo";
update submissions set institution_id=(select id from institutions where name="University of Nevada - Las Vegas") where library="UNL";
update submissions set institution_id=(select id from institutions where name="University of Nevada - Las Vegas") where library="UNLV";
update submissions set institution_id=(select id from institutions where name="University of Nevada - Las Vegas") where library="UNLV Lied Library";
update submissions set institution_id=(select id from institutions where name="University of Nevada - Las Vegas") where library="UNLV University Libraries";
update submissions set institution_id=(select id from institutions where name="The University of Virginia") where library="USA";
update submissions set institution_id=(select id from institutions where name="University of South Carolina") where library="USC Thomas Cooper";
update submissions set institution_id=(select id from institutions where name="University of Virginia") where library="UVA";
update submissions set institution_id=(select id from institutions where name="University of Virginia") where library="UVA Alderman LIBRARY";
update submissions set institution_id=(select id from institutions where name="University of Victoria") where library="UVic";
update submissions set institution_id=(select id from institutions where name="University of Victoria") where library="UVIC McPherson";
update submissions set institution_id=(select id from institutions where name="University of Victoria ") where library="UVic McPherson Library";
update submissions set institution_id=(select id from institutions where name="Hope College") where library="Van Wylen Library, Hope College";
update submissions set institution_id=(select id from institutions where name="Hope College") where library="Van Wylen Library, Hope College, Holland, Michigan";
update submissions set institution_id=(select id from institutions where name="Hope College") where library="Van Wylen, Hope College";
update submissions set institution_id=(select id from institutions where name="Victoria and Albert Museum") where library="Victoria and Albert Museum Archives (Blythe House)";
update submissions set institution_id=(select id from institutions where name="Walters Art Museum ") where library="Walters Art Museum Research Library (general stacks)";
update submissions set institution_id=(select id from institutions where name="University of Miami") where library="Weeks Music Library, University of Miami";
update submissions set institution_id=(select id from institutions where name="Wellesley College") where library="Wellesley College Clapp Library";
update submissions set institution_id=(select id from institutions where name="Harvard University") where library="Widener Library";
update submissions set institution_id=(select id from institutions where name="Mount Holyoke College") where library="Williston Library at Mount Holyoke College";
update submissions set institution_id=(select id from institutions where name="Mount Holyoke College") where library="Williston Memorial Library";
update submissions set institution_id=(select id from institutions where name="Mount Holyoke College") where library="Williston Memorial Library at Mount Holyoke College";
update submissions set institution_id=(select id from institutions where name="Mount Holyoke College") where library="Williston Memorial Library, Mount Holyoke College";
update submissions set institution_id=(select id from institutions where name="Mount Holyoke College") where library="Willitson Library at Mount Holyoke College";
update submissions set institution_id=(select id from institutions where name="Yale University") where library="Yale University Library";
delete from submission_tags where submission_id=(select id from submissions where library="Inquiring Minds Bookstore");
delete from submission_files where submission_id=(select id from submissions where library="Inquiring Minds Bookstore");
delete from submissions where library="Inquiring Minds Bookstore";
delete from submission_tags where submission_id=(select id from submissions where library="Sub basement");
delete from submission_files where submission_id=(select id from submissions where library="Sub basement");
delete from submissions where library="Sub basement";
